name: Run Nuclei Command
on:
  push:
    branches:
      - nomain
  pull_request:
    branches:
      - nomain

jobs:
  run-nuclei:
    runs-on: ubuntu-latest

    steps:
      - name: Instance 1
        uses: actions/checkout@v3

      - name: Run Docker container inside the action docker
        uses: addnab/docker-run-action@v3
        with:
            image: projectdiscovery/nuclei
            run: | 
                  export url="https://www.rossmann.dk"
                  nuclei -u $url
                  
